### ISSUE TITLE
斗內

### ISSUE THREAD

**Issue by MichaelNien** [asadman1523/QRCodeFor1922#1]
可以開一個 斗內 連結嗎 ?? 感謝

**Comment by asadman1523** [comment]
我要發大財了嗎
https://paypal.me/asadman1523?locale.x=zh_TW

**Comment by MichaelNien** [comment]
不能結案拉, 國內 不能斗內 國內的 paypal

**Comment by asadman1523** [comment]
醬喔，街口帳號行不行 900375072 👍 

不行就算了 :)

**Comment by MichaelNien** [comment]
已斗內~

**Comment by asadman1523** [comment]
第一次收到斗內，乾蝦😊

感謝斗內:
粘*家
LHT
