### ISSUE TITLE
某些疾管署 LOGO 在右下角的 QR CODE 似乎沒辦法掃

### ISSUE THREAD

**Issue by tonyhsie** [asadman1523/QRCodeFor1922#2]
你好，這個 APP 真的很方便

不過有個小問題，某些疾管署 LOGO 在右下角的 QR CODE 似乎沒辦法掃
例如：
![pxmGszHl](https://user-images.githubusercontent.com/52758827/119755511-ba20fb80-bed4-11eb-97b8-cd51926abeba.jpg)

聽說是因為 LOGO 遮住了定位點 (不太確定)

不過很多 Android QR-CODE scanner 也沒辦法掃這個 QR CODE (如 QR Droid)
這不是您的 APP 特有的問題

目前知道可以掃這種 QR CODE 的 APP，只有 Google Lens (智慧鏡頭) 而已
不過那 APP 真的不太好用 XD

如果有機會的話，還是希望自幹APP可以一併處理

非常感謝!

**Comment by asadman1523** [comment]
這個是台鐵自己的問題，寄信給台鐵吧

那個條碼掃不出來就沒辦法

tonyhsie ***@***.***> 於 2021年5月27日 週四 上午10:22 寫道：

**Comment by tonyhsie** [comment]
其實也不是台鐵而已

聽說所有公家單位的 QR CODE，都長這樣.....

不過還是謝謝你的回覆了!

**Comment by asadman1523** [comment]
已協助回報台鐵

**Comment by MichaelNien** [comment]
解析 條碼 改這個 try try ->>  https://firebase.google.com/docs/ml-kit/android/read-barcodes

**Comment by asadman1523** [comment]
> 解析 條碼 改這個 try try ->> https://firebase.google.com/docs/ml-kit/android/read-barcodes

有空再來試試看

**Comment by asadman1523** [comment]
有關您反映「台北站QRCode掃不出來」1事，經查，本站實聯制QR-Code已更新為衛生福利部疾病管制署Logo位於QR-Code中間之版本，建議您可再次嘗試掃描。

**Comment by tonyhsie** [comment]
> 有關您反映「台北站QRCode掃不出來」1事，經查，本站實聯制QR-Code已更新為衛生福利部疾病管制署Logo位於QR-Code中間之版本，建議您可再次嘗試掃描。

真的很感謝您的協助！
