### ISSUE TITLE
安卓6.0下載出現「部件分析發生問題」是什麼意思？

### ISSUE THREAD

**Issue by haochen0218** [asadman1523/QRCodeFor1922#3]

**Comment by tonyhsie** [comment]
Android 8.0 也是安裝失敗...

**Comment by asadman1523** [comment]
是安裝暗黑版嗎？先解除安裝商店版再試試

**Comment by haochen0218** [comment]
不是安裝暗黑版。已經解除安裝了，下載此版還是出現相同問題？？

**Comment by asadman1523** [comment]
請列出手機型號跟版本與安裝方式，我這邊只能用模擬器試試看

**Comment by haochen0218** [comment]
Samsung j7 2016 安卓6.0 使用apk下載

**Comment by asadman1523** [comment]
> 不是安裝暗黑版。已經解除安裝了，下載此版還是出現相同問題？？

你是下載哪個版本，android 6.0適用的APK嗎

**Comment by asadman1523** [comment]
https://github.com/asadman1523/QRCodeFor1922/releases/tag/3.1_old

我更新了，重新下載試試看

**Comment by haochen0218** [comment]
安裝成功，謝謝
