### ISSUE TITLE
關閉非實聯制QRcode提示彈窗後，掃描異常的問題

### ISSUE THREAD

**Issue by Hs0** [asadman1523/QRCodeFor1922#4]
版本：
5.0 & 5.1暗黑版
機型：
Xiaomi 10T Pro (Android11)
問題描述：
使用5.0+版本，並且在辨識到非實聯制QRcode而跳出提示彈窗時，如果不使用彈窗中的取消，而是點擊彈窗外的範圍或是直接按返回來跳出彈窗的話，會導致辨識功能在重新開啟APP前均無法使用，已知4.0以下沒有這個問題，無論是通過彈窗取消或是直接跳出彈窗都能夠繼續正常辨識

範例:

https://user-images.githubusercontent.com/14960173/134601266-3a21033d-2062-4858-8400-cee9861cedf3.mp4

已經使用這個APP很長一段時間了，無論是暗黑版能夠自動傳送簡訊，或是新版本能夠填寫同行人數都很方便，不過因為這個問題在貼有不只一個QRcode的店家(如全家)中容易複現且會打斷正常使用，所以主要還是用舊的4.0版，不知道是否有機會針對這部分進行調整呢？謝謝

**Comment by asadman1523** [comment]
Fix at version 5.2
