### ISSUE TITLE
暗黑版無法傳送簡訊

### ISSUE THREAD

**Issue by DSXVII** [asadman1523/QRCodeFor1922#6]
先前暗黑版為3.3 後續更新至5.3仍出現一樣問題
在掃描後跳轉至簡訊時有瞥到選擇發送的門號(雙卡) 但大部分時候會被簡訊app蓋過去 導致發送失敗
目前掃描約30次左右 僅5封發送成功 其中兩封有簡訊選擇框 3封直接發送
手機為小米11 系統版本MIUI13.0.1.0 Android 12
後續再補上影片

**Comment by asadman1523** [comment]
大概就是需要選擇門號，所以會跳出提示框並沒有送出

**Comment by asadman1523** [comment]
手邊沒有小米，試試看這個版本，沒問題我再merge
[app-release.zip](https://github.com/asadman1523/QRCodeFor1922/files/8399904/app-release.zip)

**Comment by DSXVII** [comment]
測試了一下還是不行 不然我就先改用一般版好了

**Comment by DSXVII** [comment]
https://user-images.githubusercontent.com/33353102/161317000-40d00f09-7895-49e1-bb33-bfe2a56dd461.mp4

補一下影片

**Comment by asadman1523** [comment]
試試看小米能不能提前預設sim卡，就能解決這個問題

**Comment by DSXVII** [comment]
我明天測試看看 
小米本身可以設定預設上網跟撥號的sim卡 但簡訊沒辦法設定 
之前我系統更新前都是預設抓卡2 現在就一定要選擇才能送出

**Comment by DSXVII** [comment]
目前狀況依舊 先改用一般版了 之後看看系統會不會更新QQ
非常感謝<(_ _)>
